apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyomio-app-core-microservice-deployment
spec:
  selector:
    matchLabels:
      app: core-microservice
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: core-microservice
      annotations:
    spec:
      containers:
        - name: "core-mircoservice"
          image: "nyomio-app-core-microservice"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key: password
            - name: DB_USER
              value: postgres
            - name: DB_URL
              value: jdbc:postgresql://postgresql.{{ .Release.Namespace }}.svc.cluster.local:5432/postgres
