apiVersion: v2
name: nyomio-app-deployment
version: 0.0.1
dependencies:
  - name: nyomio-framework
    version: 0.0.1
    repository: "file://../../../nyomio-framework/ci/helm"
  - name: nyomio-app-core-microservice
    version: 0.0.1
    repository: "file://../../core-microservice/helm"
    condition: global.coreMicroserviceEnabled
  - name: nyomio-app-nyomio-ui
    version: 0.0.1
    repository: "file://../../nyomio-ui/helm"
    condition: global.nyomIoUiEnabled
